dist: bionic
language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script:
  - bash -ex .travis-opam.sh
env:
  global:
  - PACKAGE=opam-ed
  - TESTS=true
  matrix:
  - OCAML_VERSION=4.03
  - OCAML_VERSION=4.05
  - OCAML_VERSION=4.07
  - OCAML_VERSION=4.09
  - OCAML_VERSION=4.10
os:
  - linux
  - osx
cache:
    directories:
    - $HOME/.opam
